import React from 'react';
import { Button } from '../common';
import { useQuoteRequestForm } from '../../lib';

export default function FormTester() {
    const { form } = useQuoteRequestForm();
    const [keys, setKeys] = React.useState<string[]>([]);
    const [isDev, setDev] = React.useState<boolean>(false);

    function handlePopulate() {
        form?.setData(prevData => ({
            ...prevData,
            first_name: 'TEST',
            last_name: 'TEST',
            email: 'dev@sual.co.nz',
            phone: '021 234 5678',
            mobile: '021 234 5678',
            dob: '1990-01-01',
            licence: 'Other',
            licence_other: 'Test',
            club_id: 50,
            club_membership_number: '12345',
            street_address: {
                address: '123 Street Name',
                unit: 'Level 1',
                suburb: 'Suburb',
                city: 'Auckland',
                post_code: '1234',
            },
            promo_code: 'TEST',
            declaration: {
                had_incident: true,
                incidents: [{
                    description: 'Lorem ipsum dolor sit amet.',
                    month: 'January',
                    year: '2020',
                }],
                has_demerit_points: true,
                demerit_points: '1-24',
                has_lost_licence: true,
                lost_licence_details: 'Lorem ipsum dolor sit amet.',
                was_refused_insurance: true,
                refused_insurance_details: 'Lorem ipsum dolor sit amet.',
                has_criminal_conviction: true,
                criminal_conviction_details: 'Lorem ipsum dolor sit amet.',
                has_vehicle_modifications: true,
                vehicle_modifications_details: 'Lorem ipsum dolor sit amet.',
                has_previous_insurer: true,
                previous_insurer_details: 'AA',
                previous_insurer_expires_at: '2020-01-01',
                additional_details: 'This is a test form submission generated by the computer. Please ignore it.',
            },
            vehicles: [
                {
                    make: 'Tesla',
                    model: 'Cybertruck',
                    year: '2020',
                    registration: 'ELMUSK',
                    vehicle_type: 'car',
                    product: 'star-enthusiast-prestige-everyday-plus',
                    value: 100000,
                    usage: 'Childrens car',
                    storage_location: 'Carport',
                    has_financially_interested_party: true,
                    financially_interested_party_detail: 'MTA',
                    owned_duration: 'Less than 12 months',
                    drivers: [
                        {
                            first_name: 'Test',
                            last_name: 'Test',
                            dob: '1990-01-01',
                            licence: 'NZ Class 1 (car) - Full',
                            licence_other: '',
                            relationship: 'Husband/Wife',
                        }
                    ]
                }
            ]
        }))
    }

    function handleKeydown(e: KeyboardEvent) {
        if (e.key === 'Escape') {
            return setKeys([]);
        }

        setKeys(prevKeys => [...prevKeys, e.key]);
    }

    React.useEffect(() => {
        // Detect when the user has typed the word "debug"
        if (keys.join('') === 'debug') {
            handlePopulate();
        }
    }, [keys]);

    React.useEffect(() => {
        if (typeof window !== 'undefined') {
            if (window.location.href.includes('dev')
                || window.location.href.includes('localhost')
                || window.location.href.includes('test')
                || window.location.href.includes('local')
            ) {
                setDev(true);
            }

            window.addEventListener('keydown', (e: KeyboardEvent) => handleKeydown(e));

            return () => {
                window.removeEventListener('keydown', (e: KeyboardEvent) => handleKeydown(e));
            }
        }

        return;
    }, []);

    if (isDev) {
        return (
            <Button onClick={handlePopulate} type="button" status="primary" className="fixed bottom-4 right-4">
                Populate data
            </Button>
        )
    }

    return <></>;
}
